Fix profile and promotion architecture
frontend-park-mail-ru/2021_1_YSNP pull request #67
Opened 2021-03-31 00:22 UTC by VVaria

2021-03-31 22:12 UTC, alSergey commented on public/views/PromotionView.js
Проверь отступы на странице, а так все норм. Ну по поему

2021-03-31 22:23 UTC, alSergey commented on public/components/AdPromotion/AdPromotion.hbs
> -            <label style="opacity: 0.7; margin-left: 1vw">Не продвигать объявление</label>
Ну и ты чет компоненты блоками делаешь. Вспомни БЕМ promotion-product-text, ну вот это компонент, а не текст

2021-03-31 22:23 UTC, alSergey commented on public/components/AdPromotion/AdPromotion.hbs
> -            <label style="opacity: 0.7; margin-left: 1vw">Не продвигать объявление</label>
Остальных hbs файлов нет в ПР, но я чет уверен, что там тоже проблемы с БЕМ. По нему нам будут докапываться на РК

2021-04-03 16:28 UTC, alSergey requested changes
Я с телефона смотрел, поэтому фигово посмотрел. Еби Натана, чтобы он посмотрел. В принципе все норм и сначала было, так мелкие замечания

2021-04-03 16:28 UTC, alSergey commented on public/presenters/ProductCreatePresenter.js
> +            this.__model.create(this.__view.getForm()).then(({id, status}) => {
Вынеси обработку httpStatus в модель

2021-04-03 16:28 UTC, alSergey commented on public/presenters/ProfilePresenter.js
> +        const { errorPasswordID } = this.__view.getErrorID();
Проверь линтеры. Как минимум в этой строчке будет ошибка

2021-04-03 16:28 UTC, alSergey commented on public/presenters/ProfilePresenter.js
> +                        showSuccessMessage(errorPasswordID, 'Пароль успешно изменен');
Лучше писать не if {} else {}, а 
if { return } и тут код из else

2021-04-03 16:28 UTC, alSergey commented on public/presenters/ProfilePresenter.js
> -    }
Обычно обрабатывают ошибки в блоке if {}, а потом уже выполняют основную логику

2021-04-04 22:28 UTC, nathanKith approved these changes
кайф мержи

2021-04-04 22:28 UTC, nathanKith commented on public/components/AdPromotion/AdPromotion.css
> +[id^=no-tariff] + label {
на самом деле это очень сложный селектор
я сходу только примерно понимаю, как это работает
но я не могу понять главного, почему просто не класс?

2021-04-04 22:28 UTC, nathanKith commented on public/modules/validationStates.js
> +        `;
я понял, почему ты вынесла это в валидацию, но на мой взгляд это все таки компонент
в целом не переделывай, так чиста на будущее

2021-04-05 13:00 UTC, merged